// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.8.1.0
//      SpecFlow Generator Version:1.8.0.0
//      Runtime Version:4.0.30319.261
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace STATEMACHINE.BEHAVIOR.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.8.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class UmaMaquinaDeEstadoDeveTrazerOsEstadosComAsAcoesETransicoesBaseando_SeNoPerfilDeAcessoDoUsuarioQueIniciouAMaquinaDeEstadoFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "AutorizacaoPorPerfil.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "Uma máquina de estado deve trazer os estados com as ações e transições baseando-s" +
                    "e no perfil de acesso do usuário que iniciou a máquina de estado", "\t\tComo um desenvolvedor\r\n\t\tEu quero poder definir perfis de acesso por grupos e r" +
                    "elaciona-los com os estados e suas ações", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((TechTalk.SpecFlow.FeatureContext.Current != null) 
                        && (TechTalk.SpecFlow.FeatureContext.Current.FeatureInfo.Title != "Uma máquina de estado deve trazer os estados com as ações e transições baseando-s" +
                            "e no perfil de acesso do usuário que iniciou a máquina de estado")))
            {
                STATEMACHINE.BEHAVIOR.Features.UmaMaquinaDeEstadoDeveTrazerOsEstadosComAsAcoesETransicoesBaseando_SeNoPerfilDeAcessoDoUsuarioQueIniciouAMaquinaDeEstadoFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("O perfil de acesso do usuário deve carregar seus estados")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Uma máquina de estado deve trazer os estados com as ações e transições baseando-s" +
            "e no perfil de acesso do usuário que iniciou a máquina de estado")]
        public virtual void OPerfilDeAcessoDoUsuarioDeveCarregarSeusEstados()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("O perfil de acesso do usuário deve carregar seus estados", ((string[])(null)));
#line 5
this.ScenarioSetup(scenarioInfo);
#line 6
 testRunner.Given("um usuário com perfil de officer");
#line 7
 testRunner.When("a máquina de estado é iniciada pelo usuário com perfil de officer");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Nome"});
            table1.AddRow(new string[] {
                        "Em Negociação"});
            table1.AddRow(new string[] {
                        "Desistência"});
            table1.AddRow(new string[] {
                        "Análise Crédito"});
            table1.AddRow(new string[] {
                        "Aprovado"});
#line 8
 testRunner.Then("o perfil deve validar os estados como a seguir", ((string)(null)), table1);
#line 14
 testRunner.And("os estados devem estar com as suas transições");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
